name: ssh
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache conda
      id: cache-conda
      uses: actions/cache@v3
      env:
        cache-name: cache-conda
      with:
        ## Cache the ASP dependencies. They will be created manually in the next
        ## step, after logging with ssh, and the actual caching will happen when
        ## this recipe exits. Changes to the cache cannot be saved, so it should
        ## be wiped from the web interface before starting this workflow, if
        ## desired to recreate it.
        path: |
          /usr/local/miniconda/envs
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/miniconda.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 60
      with:
        limit-access-to-actor: true
        ##limit-access-to-users: oleg-alexandrov
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
         ## Useful for saving any results produced in this session
         ## We will download this artifact
         name: ssh-test-${{ runner.os }}
         path: ~/work/StereoPipeline/packages
         retention-days: 2
      continue-on-error: true
